include(ExternalProject)
ExternalProject_Add(
        json11 PREFIX json11
        URL "https://github.com/dropbox/json11/archive/master.zip"
        # URL_HASH SHA1=fe17a0610a239311a726ecabcd2dbd669fb24ca8
        CMAKE_ARGS
        "-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>"
        "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
        CMAKE_CACHE_ARGS
        "-DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}"
        "-DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}"

)

ExternalProject_Get_Property(json11 INSTALL_DIR)
set(INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/json11)
set(JSON11_INCLUDES
        ${INSTALL_DIR}/include/${CMAKE_LIBRARY_ARCHITECTURE}
        )


set(JSON11_LIBRARIES
        ${INSTALL_DIR}/lib/${CMAKE_LIBRARY_ARCHITECTURE}/${CMAKE_STATIC_LIBRARY_PREFIX}json11${CMAKE_STATIC_LIBRARY_SUFFIX}
        )

set(JSON11_INCLUDES ${JSON11_INCLUDES} CACHE STRING "")
set(JSON11_LIBRARIES ${JSON11_LIBRARIES} CACHE STRING "")